describe('Customer Management Module', () => {
  beforeEach(() => {
    // Basic admin login setup
    cy.login('admin@zobra.test', 'admin123');
    cy.url().should('include', '/dashboard');
    cy.visit('/dashboard/customers');
  });

  it('should display KPI cards with real data', () => {
    cy.get('h1').contains('Customers');
    cy.contains('Total Customers').should('be.visible');
    cy.contains('Active Customers').should('be.visible');
    cy.contains('New This Month').should('be.visible');
    cy.contains('Repeat Customers').should('be.visible');
    cy.contains('Top Customers').should('be.visible');
  });

  it('should search customers', () => {
    // Type in search bar
    cy.get('input[placeholder="Search by name, email, phone, company..."]').type('Rakesh');
    cy.wait(500); // wait for debounce/fetch
    cy.get('table').should('be.visible');
    
    // Check if table rows exist
    cy.get('tbody tr').then($rows => {
      if ($rows.text().includes('No customers found')) {
         cy.log('Database empty, skipping row assertions');
      } else {
         cy.get('tbody tr').first().should('be.visible');
      }
    });
  });

  it('should open the Customer 360 drawer and navigate tabs', () => {
    cy.contains('Loading customers...').should('not.exist');
    cy.get('tbody tr').then($rows => {
      if (!$rows.text().includes('No customers found')) {
         // Click the second column (Name) to ensure we don't click the checkbox
         cy.get('tbody tr').first().find('td').eq(1).click();
         
         // Drawer should open and default to Overview
         cy.contains('Customer ID:', { timeout: 10000 }).should('exist');
         cy.contains('Contact Information').should('exist');
         cy.contains('Company Information').should('exist');
         cy.contains('Order Summary').should('exist');

         // Navigate to Orders Tab
         cy.contains('button', 'Orders').click();
         cy.contains('button', 'Orders').should('have.class', 'border-[#111111]');

         // Navigate to Quotes Tab
         cy.contains('button', 'Quotes').click();
         cy.contains('button', 'Quotes').should('have.class', 'border-[#111111]');
         
         // Navigate to Payments Tab
         cy.contains('button', 'Payments').click();
         cy.contains('button', 'Payments').should('have.class', 'border-[#111111]');
         
         // Navigate to Notes Tab
         cy.contains('button', 'Notes').click();
         cy.contains('button', 'Notes').should('have.class', 'border-[#111111]');
         cy.get('textarea[placeholder="Write customer notes here..."]').should('be.visible');

         // Close drawer
         cy.get('button').find('svg.lucide-x').parent().click();
         cy.contains('Customer ID:').should('not.exist');
      }
    });
  });

  it('should save internal notes correctly', () => {
     cy.contains('Loading customers...').should('not.exist');
     cy.get('tbody tr').then($rows => {
      if (!$rows.text().includes('No customers found')) {
         cy.get('tbody tr').first().find('td').eq(1).click();
         cy.contains('Customer ID:', { timeout: 10000 }).should('exist');
         cy.contains('button', 'Notes').click();
         
         const testNote = 'Test note generated by Cypress: ' + Date.now();
         cy.get('textarea[placeholder="Write customer notes here..."]').clear().type(testNote);
         cy.contains('button', 'Save Notes').click();
         cy.contains('button', 'Save Notes').should('be.visible');
         cy.get('textarea[placeholder="Write customer notes here..."]').should('have.value', testNote);
      }
     });
  });
});
